package io.crewscope.domain.execution;

public enum TaskStatus {
    CREATED,
    READY,
    RUNNING,
    WAITING_COLLABORATION,
    WAITING_REVIEW,
    WAITING_HANDOFF,
    WAITING_TAKEOVER,
    WAITING_CONFIRMATION,
    WAITING_USER_INPUT,
    WAITING_EXTERNAL_EXECUTION,
    WAITING_EVENT,
    WAITING_MANUAL,
    PAUSE_REQUESTED,
    PAUSED,
    COMPLETED,
    FAILED,
    CANCEL_REQUESTED,
    CANCELLED,
    MANUAL_TAKEOVER
}
