-- M8-A02 durable, path-free GitHub repository import jobs.
CREATE TABLE crewscope.github_repository_import_job (
    id UUID PRIMARY KEY,
    organization_id UUID NOT NULL,
    team_id UUID NOT NULL,
    project_id UUID NOT NULL,
    connection_id UUID NOT NULL,
    connection_version BIGINT NOT NULL,
    grant_id UUID NOT NULL,
    grant_version BIGINT NOT NULL,
    external_repository_id VARCHAR(100) NOT NULL,
    repository_full_name VARCHAR(511) NOT NULL,
    repository_key VARCHAR(120) NOT NULL,
    default_branch VARCHAR(255) NOT NULL,
    status VARCHAR(24) NOT NULL,
    progress_percent INTEGER NOT NULL DEFAULT 0,
    attempt INTEGER NOT NULL DEFAULT 0,
    failure_code VARCHAR(80),
    binding_id UUID,
    created_by_principal_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_github_import_target UNIQUE (organization_id, team_id, project_id, external_repository_id, repository_key),
    CONSTRAINT fk_github_import_organization FOREIGN KEY (organization_id) REFERENCES crewscope.organization(id) ON DELETE RESTRICT,
    CONSTRAINT fk_github_import_team FOREIGN KEY (team_id) REFERENCES crewscope.team(id) ON DELETE RESTRICT,
    CONSTRAINT fk_github_import_project FOREIGN KEY (project_id) REFERENCES crewscope.work_project(id) ON DELETE RESTRICT,
    CONSTRAINT fk_github_import_created_by FOREIGN KEY (organization_id, created_by_principal_id) REFERENCES crewscope.principal(organization_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_github_import_status CHECK (status IN ('REQUESTED','PREFLIGHTING','IMPORTING','READY','FAILED','CANCELLED')),
    CONSTRAINT ck_github_import_progress CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_github_import_attempt CHECK (attempt >= 0),
    CONSTRAINT ck_github_import_times CHECK (updated_at >= created_at),
    CONSTRAINT ck_github_import_binding CHECK ((status = 'READY' AND binding_id IS NOT NULL) OR status <> 'READY')
);
CREATE INDEX ix_github_import_scope ON crewscope.github_repository_import_job (organization_id, team_id, project_id, updated_at DESC);
