package io.crewscope.domain.agent;

/** Stable, non-sensitive reason returned when model execution preflight fails closed. */
public enum AgentModelPreflightRejectionCode {
    AGENT_UNAVAILABLE,
    EXECUTION_SCOPE_UNSUPPORTED,
    MODEL_BINDING_MISSING,
    ORCHESTRATION_ONLY,
    DEFAULT_MISSING,
    DEFAULT_AMBIGUOUS,
    COORDINATE_MISMATCH,
    PROVIDER_UNAVAILABLE,
    CATALOG_UNAVAILABLE,
    CONNECTION_UNAVAILABLE,
    CREDENTIAL_UNAVAILABLE,
    PRICE_UNAVAILABLE,
    CONNECTION_FORBIDDEN,
    CAPABILITY_UNSUPPORTED,
    REGION_FORBIDDEN,
    DATA_POLICY_FORBIDDEN,
    CONTEXT_LIMIT_EXCEEDED,
    OUTPUT_LIMIT_EXCEEDED,
    PRINCIPAL_INACTIVE,
    TEAM_PARTICIPATION_REQUIRED,
    RESPONSIBILITY_REQUIRED,
    BUDGET_EXHAUSTED,
    QUOTA_EXHAUSTED
}
